//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMXClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://asmx.berkalicanyildiz.com/", ConfigurationName="ServiceReference1.GeriSayimServiceSoap")]
    public interface GeriSayimServiceSoap {
        
        // CODEGEN: Generating message contract since message GetGeriSayimlarJSONSoapHeaderRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/GetGeriSayimlarJSONSoapHeader", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderResponse GetGeriSayimlarJSONSoapHeader(ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/GetGeriSayimlarJSONSoapHeader", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderResponse> GetGeriSayimlarJSONSoapHeaderAsync(ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/GetGeriSayimlarJSONParameters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetGeriSayimlarJSONParameters(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/GetGeriSayimlarJSONParameters", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetGeriSayimlarJSONParametersAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/GetGeriSayimlarJSONSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetGeriSayimlarJSONSession(string logininfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/GetGeriSayimlarJSONSession", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetGeriSayimlarJSONSessionAsync(string logininfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/LoginForSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoginForSession(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/LoginForSession", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoginForSessionAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/GetGeriSayimlarJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetGeriSayimlarJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/GetGeriSayimlarJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetGeriSayimlarJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/GetGeriSayimlarXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXClient.ServiceReference1.GeriSayim[] GetGeriSayimlarXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asmx.berkalicanyildiz.com/GetGeriSayimlarXML", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXClient.ServiceReference1.GeriSayim[]> GetGeriSayimlarXMLAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asmx.berkalicanyildiz.com/")]
    public partial class Auth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asmx.berkalicanyildiz.com/")]
    public partial class GeriSayim : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int geriSayimIDField;
        
        private string geriSayim_AdiField;
        
        private System.DateTime tarihField;
        
        private string resim_UrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int GeriSayimID {
            get {
                return this.geriSayimIDField;
            }
            set {
                this.geriSayimIDField = value;
                this.RaisePropertyChanged("GeriSayimID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GeriSayim_Adi {
            get {
                return this.geriSayim_AdiField;
            }
            set {
                this.geriSayim_AdiField = value;
                this.RaisePropertyChanged("GeriSayim_Adi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
                this.RaisePropertyChanged("Tarih");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Resim_Url {
            get {
                return this.resim_UrlField;
            }
            set {
                this.resim_UrlField = value;
                this.RaisePropertyChanged("Resim_Url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeriSayimlarJSONSoapHeader", WrapperNamespace="https://asmx.berkalicanyildiz.com/", IsWrapped=true)]
    public partial class GetGeriSayimlarJSONSoapHeaderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asmx.berkalicanyildiz.com/")]
        public ASMXClient.ServiceReference1.Auth Auth;
        
        public GetGeriSayimlarJSONSoapHeaderRequest() {
        }
        
        public GetGeriSayimlarJSONSoapHeaderRequest(ASMXClient.ServiceReference1.Auth Auth) {
            this.Auth = Auth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGeriSayimlarJSONSoapHeaderResponse", WrapperNamespace="https://asmx.berkalicanyildiz.com/", IsWrapped=true)]
    public partial class GetGeriSayimlarJSONSoapHeaderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asmx.berkalicanyildiz.com/", Order=0)]
        public string GetGeriSayimlarJSONSoapHeaderResult;
        
        public GetGeriSayimlarJSONSoapHeaderResponse() {
        }
        
        public GetGeriSayimlarJSONSoapHeaderResponse(string GetGeriSayimlarJSONSoapHeaderResult) {
            this.GetGeriSayimlarJSONSoapHeaderResult = GetGeriSayimlarJSONSoapHeaderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GeriSayimServiceSoapChannel : ASMXClient.ServiceReference1.GeriSayimServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeriSayimServiceSoapClient : System.ServiceModel.ClientBase<ASMXClient.ServiceReference1.GeriSayimServiceSoap>, ASMXClient.ServiceReference1.GeriSayimServiceSoap {
        
        public GeriSayimServiceSoapClient() {
        }
        
        public GeriSayimServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeriSayimServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeriSayimServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeriSayimServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderResponse ASMXClient.ServiceReference1.GeriSayimServiceSoap.GetGeriSayimlarJSONSoapHeader(ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderRequest request) {
            return base.Channel.GetGeriSayimlarJSONSoapHeader(request);
        }
        
        public string GetGeriSayimlarJSONSoapHeader(ASMXClient.ServiceReference1.Auth Auth) {
            ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderRequest inValue = new ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderRequest();
            inValue.Auth = Auth;
            ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderResponse retVal = ((ASMXClient.ServiceReference1.GeriSayimServiceSoap)(this)).GetGeriSayimlarJSONSoapHeader(inValue);
            return retVal.GetGeriSayimlarJSONSoapHeaderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderResponse> ASMXClient.ServiceReference1.GeriSayimServiceSoap.GetGeriSayimlarJSONSoapHeaderAsync(ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderRequest request) {
            return base.Channel.GetGeriSayimlarJSONSoapHeaderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderResponse> GetGeriSayimlarJSONSoapHeaderAsync(ASMXClient.ServiceReference1.Auth Auth) {
            ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderRequest inValue = new ASMXClient.ServiceReference1.GetGeriSayimlarJSONSoapHeaderRequest();
            inValue.Auth = Auth;
            return ((ASMXClient.ServiceReference1.GeriSayimServiceSoap)(this)).GetGeriSayimlarJSONSoapHeaderAsync(inValue);
        }
        
        public string GetGeriSayimlarJSONParameters(string username, string password) {
            return base.Channel.GetGeriSayimlarJSONParameters(username, password);
        }
        
        public System.Threading.Tasks.Task<string> GetGeriSayimlarJSONParametersAsync(string username, string password) {
            return base.Channel.GetGeriSayimlarJSONParametersAsync(username, password);
        }
        
        public string GetGeriSayimlarJSONSession(string logininfo) {
            return base.Channel.GetGeriSayimlarJSONSession(logininfo);
        }
        
        public System.Threading.Tasks.Task<string> GetGeriSayimlarJSONSessionAsync(string logininfo) {
            return base.Channel.GetGeriSayimlarJSONSessionAsync(logininfo);
        }
        
        public string LoginForSession(string username, string password) {
            return base.Channel.LoginForSession(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginForSessionAsync(string username, string password) {
            return base.Channel.LoginForSessionAsync(username, password);
        }
        
        public string GetGeriSayimlarJSON() {
            return base.Channel.GetGeriSayimlarJSON();
        }
        
        public System.Threading.Tasks.Task<string> GetGeriSayimlarJSONAsync() {
            return base.Channel.GetGeriSayimlarJSONAsync();
        }
        
        public ASMXClient.ServiceReference1.GeriSayim[] GetGeriSayimlarXML() {
            return base.Channel.GetGeriSayimlarXML();
        }
        
        public System.Threading.Tasks.Task<ASMXClient.ServiceReference1.GeriSayim[]> GetGeriSayimlarXMLAsync() {
            return base.Channel.GetGeriSayimlarXMLAsync();
        }
    }
}
